services:
  web:
    build:
      context: .
      target: runtime
    network_mode: host
    env_file: .env
    environment:
      PUBLIC_ATTACHMENT_DIR: /app/data/public-attachments
    volumes:
      - public-attachments:/app/data/public-attachments
    restart: unless-stopped

  worker:
    container_name: worker
    build:
      context: .
      target: worker
    network_mode: host
    env_file: .env
    environment:
      IMAP_PUBLIC_HOST: 0.0.0.0
      IMAP_PUBLIC_PORT: ${IMAP_PUBLIC_PORT:-993}
    restart: unless-stopped

volumes:
  public-attachments:
