services:
  web:
    build:
      context: .
      target: runtime
    env_file: .env
    environment:
      PUBLIC_ATTACHMENT_DIR: /app/data/public-attachments
    ports:
      - '3000:3000'
    volumes:
      - public-attachments:/app/data/public-attachments
    restart: unless-stopped

  worker:
    container_name: worker
    build:
      context: .
      target: worker
    env_file: .env
    restart: unless-stopped

volumes:
  public-attachments:
